[envs.original]
command = "clang {filename} -o {base}-original && ./{base}-original; echo $?"
output."original.out" = "-"
output."original.err" = "2"

[envs.tdce]
command = "(cd build && cmake ..) && make -C build TDCE && clang -fpass-plugin=build/pass/TDCE.so {filename} -o {base}-tdce; ./{base}-tdce; echo $?"
output."pass.out" = "-"
output."pass.err" = "2"
